### ISSUE TITLE
你是怎么绕过git hooks的 commit msg拦截的？

### ISSUE THREAD

**Issue by Draculabo** [Draculabo/boom#1]
@GRright

**Comment by GRright** [comment]
我没有尝试绕开，应该就是单纯地提交成功了，下回我按那个提交的模板来编辑吧。
&nbsp;


zhang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月17日(星期二) 中午1:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [Draculabo/boom] 你是怎么绕过git hooks的 commit msg拦截的？ (Issue #1)





 
@GRright
